sudo: required

language: javascript

services:
    - docker

before_install:
    - ls /var/lib/docker
    - docker build -t demo-app .

script:
    - docker run -it --rm demo-app

cache:
    directories:
        - /var/lib/docker/
